/**
 * AI-generated district risk analysis card.
 * Displays vulnerability score, key findings, and recommendations
 * generated by Google Gemini via Genkit.
 */

"use client";

import { useState, useTransition } from "react";
import type { District } from "@/lib/district-data";
import type { DistrictSummaryOutput } from "@/ai/flows/generate-district-summary-flow";
import { handleGenerateDistrictSummary } from "@/app/actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Brain,
  LoaderCircle,
  AlertTriangle,
  CheckCircle2,
  Target,
  DollarSign,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface DistrictSummaryCardProps {
  district: District;
}

function PriorityBadge({ level }: { level: string }) {
  const colors: Record<string, string> = {
    IMMEDIATE: "bg-red-500/20 text-red-400 border-red-500/30",
    HIGH: "bg-orange-500/20 text-orange-400 border-orange-500/30",
    MODERATE: "bg-amber-500/20 text-amber-400 border-amber-500/30",
    LOW: "bg-green-500/20 text-green-400 border-green-500/30",
  };

  return (
    <span
      className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider border ${colors[level] ?? colors.MODERATE}`}
    >
      {level}
    </span>
  );
}

function VulnerabilityGauge({ score }: { score: number }) {
  const color =
    score >= 75
      ? "text-red-400"
      : score >= 50
        ? "text-orange-400"
        : score >= 25
          ? "text-amber-400"
          : "text-green-400";

  const circumference = 2 * Math.PI * 40;
  const strokeDashoffset = circumference - (score / 100) * circumference;

  return (
    <div className="relative flex items-center justify-center w-24 h-24">
      <svg className="transform -rotate-90 w-24 h-24" viewBox="0 0 100 100">
        <circle
          cx="50"
          cy="50"
          r="40"
          stroke="currentColor"
          strokeWidth="8"
          fill="none"
          className="text-muted/30"
        />
        <circle
          cx="50"
          cy="50"
          r="40"
          stroke="currentColor"
          strokeWidth="8"
          fill="none"
          strokeLinecap="round"
          className={color}
          style={{
            strokeDasharray: circumference,
            strokeDashoffset,
            transition: "stroke-dashoffset 1s ease-out",
          }}
        />
      </svg>
      <div className="absolute flex flex-col items-center">
        <span className={`text-xl font-bold ${color}`}>{score}</span>
        <span className="text-[9px] text-muted-foreground uppercase">Risk</span>
      </div>
    </div>
  );
}

function SummaryContent({ summary }: { summary: DistrictSummaryOutput }) {
  return (
    <div className="space-y-4 mt-4">
      {/* Score + Priority */}
      <div className="flex items-center gap-4">
        <VulnerabilityGauge score={summary.vulnerabilityScore} />
        <div className="flex-1 space-y-2">
          <div className="flex items-center gap-2">
            <PriorityBadge level={summary.priorityLevel} />
            <div className="flex items-center gap-1 text-xs text-muted-foreground">
              <DollarSign className="h-3 w-3" />
              {summary.estimatedBudget}
            </div>
          </div>
          <p className="text-sm text-primary-foreground/90 leading-relaxed">
            {summary.riskAssessment}
          </p>
        </div>
      </div>

      {/* Key Findings */}
      <div>
        <h4 className="flex items-center gap-1.5 text-xs font-semibold text-primary-foreground uppercase tracking-wider mb-2">
          <AlertTriangle className="h-3.5 w-3.5 text-amber-400" />
          Key Findings
        </h4>
        <ul className="space-y-1.5">
          {summary.keyFindings.map((finding, i) => (
            <li
              key={i}
              className="text-sm text-muted-foreground pl-4 relative before:absolute before:left-0 before:top-2 before:w-1.5 before:h-1.5 before:rounded-full before:bg-amber-400/50"
            >
              {finding}
            </li>
          ))}
        </ul>
      </div>

      {/* Recommendations */}
      <div>
        <h4 className="flex items-center gap-1.5 text-xs font-semibold text-primary-foreground uppercase tracking-wider mb-2">
          <Target className="h-3.5 w-3.5 text-primary" />
          Recommendations
        </h4>
        <ul className="space-y-1.5">
          {summary.recommendations.map((rec, i) => (
            <li
              key={i}
              className="flex items-start gap-2 text-sm text-muted-foreground"
            >
              <CheckCircle2 className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
              <span>{rec}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default function DistrictSummaryCard({
  district,
}: DistrictSummaryCardProps) {
  const [summary, setSummary] = useState<DistrictSummaryOutput | null>(null);
  const [isPending, startTransition] = useTransition();
  const { toast } = useToast();

  const onGenerate = () => {
    setSummary(null);
    startTransition(async () => {
      const result = await handleGenerateDistrictSummary({
        name: district.name,
        heatRisk: district.heatRisk,
        heatIndex: district.heatIndex,
        population: district.population,
        greenSpacePercentage: district.greenSpacePercentage,
        pollutionRate: district.pollutionRate,
        acAccessPercentage: district.acAccessPercentage,
        communityFacilities: district.communityFacilities,
        identifiedNeeds: district.identifiedNeeds,
        violationsCount: district.violationsCount,
        crimeCount: district.crimeCount,
      });
      if (result.summary) {
        setSummary(result.summary);
      } else if (result.error) {
        toast({
          variant: "destructive",
          title: "Analysis Failed",
          description: result.error,
        });
      }
    });
  };

  return (
    <Card className="bg-card/70 border-primary/20">
      <CardHeader className="pb-2">
        <div className="flex items-center space-x-3">
          <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-primary/15">
            <Brain className="h-5 w-5 text-primary" />
          </div>
          <div className="flex-1">
            <CardTitle className="text-lg text-primary-foreground">
              Risk Analysis
            </CardTitle>
            <p className="text-[11px] text-muted-foreground leading-snug mt-0.5">
              AI-powered vulnerability assessment with risk scoring, key
              findings, and prioritized intervention recommendations
            </p>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {!summary && (
          <Button
            onClick={onGenerate}
            disabled={isPending}
            variant="outline"
            className="w-full border-primary/30 hover:bg-primary/10"
          >
            {isPending ? (
              <LoaderCircle className="animate-spin mr-2 h-4 w-4" />
            ) : (
              <Brain className="mr-2 h-4 w-4" />
            )}
            {isPending ? "Analyzing..." : `Analyze ${district.name}`}
          </Button>
        )}

        {isPending && !summary && (
          <div className="mt-4 space-y-3">
            <div className="flex items-center gap-4">
              <div className="w-24 h-24 rounded-full bg-muted/30 animate-pulse" />
              <div className="flex-1 space-y-2">
                <div className="h-4 w-20 rounded bg-muted/30 animate-pulse" />
                <div className="h-3 w-full rounded bg-muted/30 animate-pulse" />
                <div className="h-3 w-3/4 rounded bg-muted/30 animate-pulse" />
              </div>
            </div>
            <div className="space-y-2">
              <div className="h-3 w-full rounded bg-muted/30 animate-pulse" />
              <div className="h-3 w-5/6 rounded bg-muted/30 animate-pulse" />
              <div className="h-3 w-4/5 rounded bg-muted/30 animate-pulse" />
            </div>
          </div>
        )}

        {summary && <SummaryContent summary={summary} />}
      </CardContent>
    </Card>
  );
}
